{
 "title": "Finances",
 "description": "My finances summary",
 "time": { "from": "2019-01-01T02:00:00.000Z", "to": "2019-07-02T02:59:59.999Z" },
 "panels": [
  { "title": "Sumary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current balance",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "format": "currencyBRL",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wallet",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accounts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "xp",
     "measurement": "wallet",
     "query": "SELECT \"value\" FROM \"wallet\" WHERE (\"source\" = 'xp') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "xp" }
     ]
    },
    {
     "alias": "itau",
     "measurement": "wallet",
     "query": "SELECT \"value\" FROM \"wallet\" WHERE (\"source\" = 'itau') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "itau" }
     ]
    },
    {
     "alias": "inter",
     "measurement": "wallet",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "inter" }
     ]
    }
   ]
  },
  {
   "title": "Accounts Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "wallet",
     "query": "SELECT \"value\" FROM \"wallet\" WHERE (\"source\" = 'xp') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Investments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Actives",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "slug" ], "type": "tag" }
     ],
     "measurement": "investments",
     "select": [
      [
       { "params": [ "balance" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Investments",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "slug" ], "type": "tag" }
     ],
     "measurement": "investments",
     "query": "SELECT sum(\"amout\") FROM \"investments\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "slug" ], "type": "tag" }
     ],
     "measurement": "investments",
     "select": [
      [
       { "params": [ "balance" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "variable",
     "measurement": "investments",
     "query": "SELECT sum(\"balance\") FROM \"investments\" WHERE slug =~ /^[itsa4|bid4]/ AND $timeFilter",
     "select": [
      [
       { "params": [ "balance" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "slug", "operator": "=", "value": "itsa4" }
     ]
    },
    {
     "alias": "fixed",
     "measurement": "investments",
     "select": [
      [
       { "params": [ "balance" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "slug", "operator": "=", "value": "selic2025" }
     ]
    }
   ]
  },
  {
   "title": "Cumulative Dividends",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "slug" ], "type": "tag" }
     ],
     "measurement": "investments",
     "select": [
      [
       { "params": [ "fee" ], "type": "field" },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Investments Fees",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 16 },
   "format": "currencyBRL",
   "valueName": "current",
   "targets": [
    {
     "measurement": "dividends",
     "select": [
      [
       { "params": [ "fee" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dividends Fees",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 19 },
   "format": "currencyBRL",
   "valueName": "current",
   "targets": [
    {
     "measurement": "investments",
     "select": [
      [
       { "params": [ "fee" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}